version: '3'

services:
  # MySQL
  database:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql/log:/var/log/mysql
    - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    networks:
      - rust-net

networks:
  rust-net:
    driver: bridge