version: '3'
services:
    rust:
        build:
          context: .devcontainer
          dockerfile: Dockerfile
        volumes:
          - .:/usr/src/app
        environment:
          - USER=`${USER}`
        stdin_open: true